### ISSUE TITLE
error with _C file

### ISSUE THREAD

**Issue by sv176** [hiroyasuakada/mask-processing#1]
Hi hiroyasuakada,

I recently got in touch with you via Twitter regarding your implementation. I have been able to solve the fvcore issue (required stating the whole path when importing a function from the file).
However, I have been receiving an error when running process.py 

`  File "/path/Mask-RCNN-Detectron2-for-Human-Extraction-master/detectron2_repo_with_revision/detectron2/layers/deform_conv.py", line 10, in <module>`
` from detectron2_repo_with_revision.detectron2 import _C`
`ImportError: cannot import name '_C' from 'detectron2_repo_with_revision.detectron2' (/path/Mask-RCNN-Detectron2-for-Human-Extraction-master/detectron2_repo_with_revision/detectron2/__init__.py)`

I tried finding the _C file but haven't been able to. I also attempted to find the functions given in the _C file through searching on the directory, but have been unsuccessful in finding it. 

Many Thanks,
sv176

**Comment by hiroyasuakada** [comment]
Thank you for your interest and questions! 

Since this repository is old, I slightly updated it just before, including the instruction and the docker file.
Can you please clone the repo and try again?

Best,
Hiroyasu
